name: Nix flake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-flake:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - name: Build container image
        run: nix build .#dockerImage
      - name: Load image
        run: docker load < result
      - name: Log in to ghcr.io
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag image
        if: ${{ github.event_name == 'push' }}
        run: docker tag codex-universal:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Push image
        if: ${{ github.event_name == 'push' }}
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

