name: Nix flake build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10
      - name: Set up cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Build container image
        run: nix build .#dockerImage

